---
- hosts: compute_nodes:storage_nodes
  become_user: root
  become: yes

  tasks:
# Permit all access over the loopback interface.  This could
# # be tightened as well, but to do so would effect some of
# # the administrative functions.
# restrict 127.0.0.1 
# restrict ::1
#
  - name: Controller NTP configuration | remove IPv4 localhost restriction
    lineinfile:
      dest: "/etc/ntp.conf"
      regexp: "^server"
      line:   "server ctrl.example.com iburst"

  - name: Controller NTP configuration | Enable NTP service
    service:
      name: ntpd
      enabled: yes
      state: started
